apiVersion: v1
kind: PersistentVolume
metadata:
  name: brockeragefirm-db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /var/lib/postgresql/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brockeragefirm-db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brockeragefirm-db
  labels:
    app: brockeragefirm-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brockeragefirm-db
  template:
    metadata:
      labels:
        app: brockeragefirm-db
    spec:
      volumes:
        - name: brockeragefirm-db-pv-storage
          persistentVolumeClaim:
            claimName: brockeragefirm-db-pvc
      containers:
        - name: brockeragefirm-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: Passw0rd123
            - name: POSTGRES_DB
              value: brokeragefirm
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: brockeragefirm-db-pv-storage

---
apiVersion: v1
kind: Service
metadata:
  name: brockeragefirm-db-service
spec:
  type: ClusterIP
  ports:
    - name: "brockeragefirm-db"
      port: 5432
      targetPort: 5432
  selector:
    app: brockeragefirm-db
